# Kitty Configuration

# Font Configuration
font_family JetBrainsMono Nerd Font
font_size 12.0


# macOS Specific Settings
macos_option_as_alt left
macos_titlebar_path hidden
#hide_window_decorations titlebar-only

# Tmux Integration
allow_remote_control yes
listen_on unix:/tmp/kitty-{kitty_pid}

# Shell integration (enables better tmux support)
shell_integration enabled

# Visual Effects (commented out - uncomment to enable)
# background_opacity 0.80
# background_blur 30

# Window Settings
# hide_window_decorations titlebar-only
# window_padding_width 2

# cursor
cursor_trail 2
